export const GET_COURSE_LIST_REQUEST = 'GET_COURSE_LIST_REQUEST';
export const GET_COURSE_LIST_SUCCESS = 'GET_COURSE_LIST_SUCCESS';
export const GET_COURSE_LIST_FAIL = 'GET_COURSE_LIST_FAIL';

export const GET_COURSE_ITEM_REQUEST = 'GET_COURSE_ITEM_REQUEST';
export const GET_COURSE_ITEM_SUCCESS = 'GET_COURSE_ITEM_SUCCESS';
export const GET_COURSE_ITEM_FAIL = 'GET_COURSE_ITEM_FAIL';